Travis errors trial v2
Trying to track down Travis failures with:

[33mNoMethodError: undefined method `spec' for nil:NilClass[0m
[31mAn error occurred while installing minitest-reporters (1.1.7), and Bundler cannot continue.
Make sure that `gem install minitest-reporters -v '1.1.7'` succeeds before bundling.[0m

There's differences in the gem versions, between current faiures and previous successful version. I have therefore locked down the gem versions to the same as a trial to see if that's the problem.

Nothing inside my code changes seems to trigger error localy.